[package]
name = "idl2json_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "idl2json"
path = "src/main.rs"

[dependencies]
candid = "0.6.21"
serde_json = "^1.0"
idl2json = { path = "../idl2json" }
