[workspace]

members = [
  "src/idl2json",
  "src/idl2json_cli",
  "src/yaml2candid",
  "src/yaml2candid_cli",
]

resolver = "2"

[workspace.package]
version = "0.9.3-alpha.1"

[workspace.dependencies]
candid = { version = "0.9.0", features = ["parser"] }
