[package]
name = "idl2json"
version = "0.1.0"
authors = ["Max <max@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.6.17"
serde_json = "1.0.64"
